/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wangjunjian_class_parameter_ClassParameter */

#ifndef _Included_com_wangjunjian_class_parameter_ClassParameter
#define _Included_com_wangjunjian_class_parameter_ClassParameter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wangjunjian_class_parameter_ClassParameter
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wangjunjian_class_1parameter_ClassParameter_hello
  (JNIEnv *, jobject);

/*
 * Class:     com_wangjunjian_class_parameter_ClassParameter
 * Method:    faceDetect
 * Signature: ()Landroid/graphics/Rect;
 */
JNIEXPORT jobject JNICALL Java_com_wangjunjian_class_1parameter_ClassParameter_faceDetect
  (JNIEnv *, jobject);

/*
 * Class:     com_wangjunjian_class_parameter_ClassParameter
 * Method:    facesDetect
 * Signature: ()Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_com_wangjunjian_class_1parameter_ClassParameter_facesDetect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
